[package]
name = "redeliste-cli"
version = "0.1.0"
edition = "2021"
authors = ["FlorianXXIV"]
license = "EUPL-1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
